services:
  db:
    # Usamos PostGIS: un PostgreSQL con superpoderes para mapas y coordenadas
    image: postgis/postgis:15-3.3
    container_name: skypalette_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: superpassword
      POSTGRES_DB: skypalette
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: